# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c8f8c8ed311c63f74fb918213c34b68d2c12c177a75b244ce4b323d5ef34723634507cdc9b10c75361c99b77258ad4605804b965ff2ec031dcf4ed468e6bd1a

test:
  secret_key_base: 9c8dddc52a7003fc7b4a52a44ef5493065c4eb3daf1a901526b7c9039a400fd86c0e497e8d68160778355de6ebe0dbc5f9c69efbda01bf0876fd4282cc3a7bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
